### ISSUE TITLE
duplicated option?

### ISSUE THREAD

**Issue by highzclouds** [sdss/mangadap#117]
trying to run mangadap for the first time.  getting 15 of the following errors when running "pytest . -W ignore".  how do I fix this?

configparser.DuplicateOptionError: While reading from '<dict>': option 'host' in section 'DEFAULT' already exists

**Comment by kbwestfall** [comment]
Hi @highzclouds .  Can you post the details of your system (OS, python version, mangadap version and/or branch), and post the full output from the `pytest` command?   For reference, I just ran the tests using on my Mac (Sonoma 14.4.1) with python 3.12.2 on the `main` branch and everything passed successfully.

**Comment by highzclouds** [comment]
Hi, I created a virtual environment and re-ran everything.  The problem is fixed now.   Thank you for checking.
