### ISSUE TITLE
issue with velocity of the Hzeta emission line

### ISSUE THREAD

**Issue by francbelf** [sdss/mangadap#16]
Adam discovered a problem with the fit to Hzeta emission line. The problem is a subtle mismatch in velocity between the data and the emission line model. See the example below.

![problem_with_hz](https://user-images.githubusercontent.com/20231691/42600460-40e70114-8517-11e8-8eba-82645d22ba5e.png)

It seems to me that this is a DAP bug, but I'm not sure. Here's the checks I have done:

1. I checked that the wavelength of the line is correct in the input par file, the vacuum to air correction is correctly taken into account inside the code (there is no correction in the DAP as both the input wavelength and data are in vacuum). Moreover Kyle helped me to check that the Gaussian template used as input to the ppxf fit in the DAP is produced at the correct velocity.

2. I checked the problem is still present using different MaNGA galaxies using my fit_one_spectrum code, which uses the DAP functionality to fit a single MaNGA spaxel. The problem is also present if I fit a SDSS spectrum (remember these were taken with the old SDSS spectrograph) with the same code, so it's not MaNGA-specific.

3. I then ditched the DAP and fitted the same spectrum with pPXF (and a wrapper of my own writing). This fit uses different parameters and logic than the DAP functions. It turns out that the problem is *not* present in this case. So I conclude the problem is due to a bug/problem in the MaNGA DAP.

4. I tested using fit_one_spectrum using different tying strategies. If I set the velocity of Hzeta to be free (and not tied to the other emission lines) the resulting fit is good. I get out a velocity which is ~25 km/s bluer than all other lines.

At this point I am at a loss. I am going to report the issue on the DAP GitHub and leave it there. I am not sure why doing my own ppxf fit gives a good fit on the same spectrum, while using the DAP functions the Hzeta velocity needs to be offset by ~25 km/s.

**Comment by kbwestfall** [comment]
The HeI 3889 line has been successfully added to the `mpl8` and will be merged to `master` soon.  Also added the NI 5199,5201 doublet.  Closing.
