### ISSUE TITLE
Failure of the test module

### ISSUE THREAD

**Issue by francbelf** [sdss/mangadap#33]
The DAP test module fails in test_sasuke

======================================================= FAILURES =======================================================
_____________________________________________________ test_sasuke ______________________________________________________

    def test_sasuke():
        # Read the data
        specfile = data_file('MaNGA_test_spectra.fits.gz')
        hdu = fits.open(specfile)
        drpbm = DRPFitsBitMask()
        flux = numpy.ma.MaskedArray(hdu['FLUX'].data,
                                    mask=drpbm.flagged(hdu['MASK'].data, DRPFits.do_not_fit_flags()))
        ferr = numpy.ma.power(hdu['IVAR'].data, -0.5)
        flux[ferr.mask] = numpy.ma.masked
        ferr[flux.mask] = numpy.ma.masked
        nspec = flux.shape[0]
    
        # Instantiate the template libary
        velscale_ratio = 4
        tpl = TemplateLibrary('MILESHC', match_to_drp_resolution=False, velscale_ratio=velscale_ratio,
                              spectral_step=1e-4, log=True, hardcopy=False)
        tpl_sres = numpy.mean(tpl['SPECRES'].data, axis=0)
    
        # Get the pixel mask
        pixelmask = SpectralPixelMask(artdb=ArtifactDB('BADSKY'), emldb=EmissionLineDB('ELPFULL'))
    
        # Instantiate the fitting class
        ppxf = PPXFFit(StellarContinuumModelBitMask())
    
        # Perform the fit
        sc_wave, sc_flux, sc_mask, sc_par \
            = ppxf.fit(tpl['WAVE'].data.copy(), tpl['FLUX'].data.copy(), hdu['WAVE'].data, flux, ferr,
                       hdu['Z'].data, numpy.full(nspec, 100.), iteration_mode='no_global_wrej',
                       reject_boxcar=100, ensemble=False, velscale_ratio=velscale_ratio,
                       mask=pixelmask, matched_resolution=False, tpl_sres=tpl_sres,
                       obj_sres=hdu['SRES'].data, degree=8, moments=2)
    
        # Mask the 5577 sky line
        pixelmask = SpectralPixelMask(artdb=ArtifactDB('BADSKY'))
    
        # Read the emission line fitting database
        emldb = EmissionLineDB('ELPMILES')
        assert emldb['name'][18] == 'Ha', 'Emission-line database names or ordering changed'
    
        # Instantiate the fitting class
        emlfit = Sasuke(EmissionLineModelBitMask())
    
        # Perform the fit
        el_wave, model, el_flux, el_mask, el_fit, el_par \
                = emlfit.fit(emldb, hdu['WAVE'].data, flux, obj_ferr=ferr, obj_mask=pixelmask,
                             obj_sres=hdu['SRES'].data, guess_redshift=hdu['Z'].data,
                             guess_dispersion=numpy.full(nspec, 100.), reject_boxcar=101,
                             stpl_wave=tpl['WAVE'].data, stpl_flux=tpl['FLUX'].data,
                             stpl_sres=tpl_sres, stellar_kinematics=sc_par['KIN'],
                             etpl_sinst_mode='offset', etpl_sinst_min=10.,
                             velscale_ratio=velscale_ratio, matched_resolution=False) #, # mdegree=8,
                             #plot=True)
    
        # Test the results
    
        # Rejected pixels
        assert numpy.sum(emlfit.bitmask.flagged(el_mask, flag='PPXF_REJECT')) == 277, \
                    'Different number of rejected pixels'
    
        # Unable to fit
        assert numpy.array_equal(emlfit.bitmask.flagged_bits(el_fit['MASK'][5]), ['NO_FIT']), \
                    'Expected NO_FIT in 6th spectrum'
    
        # Number of used templates
        assert numpy.array_equal(numpy.sum(el_fit['TPLWGT'] > 0, axis=1),
                                 [25, 24, 32, 32, 28,  0, 17, 22]), \
                    'Different number of templates with non-zero weights'
    
        # No additive coefficients
        assert numpy.all(el_fit['ADDCOEF'] == 0), \
                    'No multiplicative coefficients should exist'
    
        # No multiplicative coefficients
        assert numpy.all(el_fit['MULTCOEF'] == 0), \
                    'No multiplicative coefficients should exist'
    
        # Fit statistics
        assert numpy.allclose(el_fit['RCHI2'],
                        numpy.array([2.30526714, 1.19355894, 1.54887132, 1.84447282, 3.14657599,
                                     0.        , 1.03495789, 0.86928516])), 'Chi-square different'
    
        assert numpy.allclose(el_fit['RMS'],
                        numpy.array([0.03624053, 0.0191412 , 0.03661278, 0.02454041, 0.05073471,
                                     0.        , 0.01283324, 0.01245004])), 'RMS different'
    
>       assert numpy.allclose(el_fit['FRMS'],
                        numpy.array([0.02098079, 0.02650329, 0.02718797, 0.03478277, 0.01857   ,
                                     0.        , 1.12984714, 0.10961989])), 'Fractional RMS different'
E       AssertionError: Fractional RMS different
E       assert False
E        +  where False = <function allclose at 0x7fd473a5fa60>(array([0.02098079, 0.02650329, 0.02718797, 0.03478063, 0.01857   ,\n       0.        , 1.12984714, 0.10961989]), array([0.02098079, 0.02650329, 0.02718797, 0.03478277, 0.01857   ,\n       0.        , 1.12984714, 0.10961989]))
E        +    where <function allclose at 0x7fd473a5fa60> = numpy.allclose
E        +    and   array([0.02098079, 0.02650329, 0.02718797, 0.03478277, 0.01857   ,\n       0.        , 1.12984714, 0.10961989]) = <built-in function array>([0.02098079, 0.02650329, 0.02718797, 0.03478277, 0.01857, 0.0, ...])
E        +      where <built-in function array> = numpy.array

python/mangadap/tests/test_sasuke.py:122: AssertionError
------------------------------------------------- Captured stdout call -------------------------------------------------
--------------------------------------------------

**Comment by kbwestfall** [comment]
Added `setuptools>=27.3` to `requirements.txt` in MPL-9.
