### ISSUE TITLE
Dealing with regular wavelength spacing in templatelibrary.py

### ISSUE THREAD

**Issue by khrrubin** [sdss/mangadap#59]
In _process_library, ang_per_pix needs to have the same dimensions as self.hdu['SPECRES'].data.  However, if regular=True in the line

ang_per_pix = numpy.array([angstroms_per_pixel(w, log=self.library['log10'], base=10., regular=self.library['in_vacuum'])....

then ang_per_pix ends up having dimensions of (1 x number of templates), which causes the next line to crash (i.e., pix_per_fwhm = numpy.ma.divide(self.hdu['WAVE'].data,
                                       self.hdu['SPECRES'].data * ang_per_pix)

**Comment by kbwestfall** [comment]
This should now be fixed by #67
