### ISSUE TITLE
Line-list additions for MPL-9

### ISSUE THREAD

**Issue by mabershady** [sdss/mangadap#62]
I recommend adding the following to our line-list. These are wavelengths in AIR.

Anything with "<<" after it I have seen in strongly star-forming regions. Two fine examples can be found on plate 8252: 8252-6103 and 8252-9102. 

Anything with "(<<)" -- mostly the upper Balmer and Paschen sequence I have not but it is in our wavelength range. P-delta should be for some of our lower redshift objects.

thanks,
Matt

3686.831        H19 (<<)
3691.551        H18 (<<)
3697.157        H17 (<<)
3703.859        H16 (<<)
3711.977        H15 (<<)
3721.945        H14 <<
3734.369        H13 <<
3750.158        H12 <<
3770.637        H11 <<
4068.600        [S II] <<
4076.349        [S II] <<
4363.210        [O III] <<
4471.479        He I    <<
5200.257        [N I]  <<
6679.996        He I  <<
7065.196        He I   << 
7135.790        [Ar III]  <<
7319.990        [O II]  <<
7330.730        [O II]  <<
7751.060        [Ar III] <<
8392.397        Pa20 (<<)
8413.318        Pa19 (<<)
8437.956        Pa18 (<<)
8467.254        Pa17 (<<)
8502.483        Pa16 <<
8545.383        Pa15 <<
8598.392        Pa14 <<
8665.019        Pa13 <<
8750.472        Pa12 <<
8862.782        Pa11 <<
9014.909        Pa10 <<
9229.014        Pa9 <<
9545.969        Pa epsilon <<
10049.368      Pa delta (<<)

**Comment by kbwestfall** [comment]
Hi @mabershady 

For MPL-9, I've added 10 lines compared to MPL-8:

H12     3751.2243
H11     3771.7080
HeI     7067.1252
ArIII   7137.76
ArIII   7753.24
Peta    9017.384
SIII    9071.1
Pzet    9231.546
SIII    9533.2
Peps    9548.588

This was based on your off-line minimal suggestion and based on some cursory tests.  I've also added a parameter file that contains all 57 lines that I ran during an early test.  See https://github.com/sdss/mangadap/blob/mastar/data/emission_lines/elpmab.par

I'm going to soon merge the `mastar` branch, so this file will be at `data/emission_lines/elpmab.par` in the `master` branch.

Even with the shortened list, there can still be some weird artifacts in the maps of the fit-residual RMS for the emission-line module.  We should figure this out in-between MPL-9 and MPL-10.
