### ISSUE TITLE
Unable to import EmissionLineDBDef

### ISSUE THREAD

**Issue by yuanzeluo** [sdss/mangadap#68]
Hi, I'm trying to fit some emission lines that are not in the existing emission line database by creating my own .par file and follow
```
from mangadap.par.emissionlinedb import EmissionLineDBDef
from mangadap.par.emissionlinedb import EmissionLineDB
d = EmissionLineDBDef(key='USER',
                      file_path='/path/to/parameter/file',
                      in_vacuum=True)
p = EmissionLineDB('USER', emldb_list=d)
```
However, I got error
```
ImportError: cannot import name 'EmissionLineDBDef' from 'mangadap.par.emissionlinedb' (/Users/yl/opt/anaconda3/lib/python3.7/site-packages/sdss_mangadap-2.4.1-py3.7.egg/mangadap/par/emissionlinedb.py)
```

I can successfully import `EmissionLineDB` from `mangadap.par.emissionlinedb` though.

Many thanks!

**Comment by kbwestfall** [comment]
Sorry, this is old and/or erroneous documentation.  The bit of code you want is:

```
from mangadap.par.spectralfeaturedb import SpectralFeatureDBDef
from mangadap.par.emissionlinedb import EmissionLineDB

d = SpectralFeatureDBDef(key='USER', file_path='/path/to/parameter/file')
p = EmissionLineDB('USER', emldb_list=d)
```

Note that the definition of the lines as being in vacuum or air is now included in the .par file.

**Comment by yuanzeluo** [comment]
This works. Thank you so much!

I actually see some of the lines I want commented out in the elpmpl9.par file, and you noted "they cause issue in the fit-quality metrics that aren't yet understood."

If I use dap procedure to fit for the flux of these weak lines on stacked spectra (which are supposed to have boosted SNR), would fitting provide reliable results?

**Comment by kbwestfall** [comment]
Great!  Glad to hear it.

Right, if you look at the RMS maps posted in #66 (middle left panel in each figure), you'll see structure in the top figure that isn't in the bottom figure.  It's unclear where this comes from, and it could simply be a minor problem with the RMS computation itself.  Note that the structure appears in regions with very low continuum S/N and line flux.

For higher S/N stacks, the procedure should be fine, but you should inspect the fits and the chi-square value and make a judgement based on that.
